name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry using PAT
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push web image
      run: |
        REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        docker build -t ghcr.io/$REPO_OWNER/ass3-web-web:latest ./web
        docker push ghcr.io/$REPO_OWNER/ass3-web-web:latest

    - name: Build and push db image
      run: |
        REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        docker build -t ghcr.io/$REPO_OWNER/ass3-web-db:latest ./db
        docker push ghcr.io/$REPO_OWNER/ass3-web-db:latest
